DROP TABLE IF EXISTS ARTICLES;

CREATE TABLE ARTICLES (
  id UUID NOT NULL,
  title VARCHAR(250) NOT NULL,
  author_name VARCHAR(250) NOT NULL,
  preview_content VARCHAR(200) NOT NULL,
  content VARCHAR(500) NOT NULL,
  image_url VARCHAR(250) NOT NULL,
  creation_date DATETIME NOT NULL,

  PRIMARY KEY(id)
);
