server:
  servlet:
    contextPath: /blogi

spring:
  mvc:
    view:
      suffix: .html
  web:
    resources:
      static-locations: classpath:/static/html, classpath:/static/css, classpath:/static/js
  datasource:
    url: jdbc:h2:mem:blogi
    username: admin
    password: admin
    schema: classpath:/database-scripts/schema.sql
    data: classpath:/database-scripts/data.sql
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-db